name: Build and Publish to Cloudsmith

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install conan
      - run: conan remote add sparesparrow-conan https://conan.cloudsmith.io/sparesparrow-conan/openssl-conan/ --force
      - run: conan create . --build=missing
      - env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          conan remote login sparesparrow-conan spare-sparrow --password "$CLOUDSMITH_API_KEY"
          conan upload "openssl-fips-data/*" -r=sparesparrow-conan --all --confirm
